### ISSUE TITLE
when will bii-server take place here?

### ISSUE THREAD

**Issue by timo0** [biicode/bii-server#1]
topic describe all :)

**Comment by drodri** [comment]
Hi timo, we have certainly not forgotten about this, it was planned for 1st July, keep tuned!

**Comment by SrTobi** [comment]
will this enable us to host an own server with private blocks? Can't wait for it

**Comment by lasote** [comment]
Yes!

**Comment by MarceloEmmerich** [comment]
please hurry guys! :-)

**Comment by lasote** [comment]
Toc Toc! Its here! ;)

**Comment by timo0** [comment]
Thanks!

**Comment by MarceloEmmerich** [comment]
YES!! Thanks!

**Comment by SrTobi** [comment]
Nice. After hours trying to setup the bii server I finally got him running! Unfortunately something is still wrong with the authentication... nja I will investigate tomorrow!^^ Thanks for make it open source.

**Comment by lasote** [comment]
@SrTobi if you found some wrong step in readme or missing information feel free to open a pull request! I know the readme is not perfect. If I can help you with the auth write me! I'm really glad you are using biicode open source server :D

**Comment by SrTobi** [comment]
I there a way to make a block private?
And is there a webinterface like biicode.com?

**Comment by lasote** [comment]
No, web and webapi are not released as open source by now.

About making private blocks, well, its not allowed from client and admin
script from server only allows user creation. For handle permissions its
necessary write new admin scripts or develop a new feature in client and
server.
